/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myproject;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author S
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPAge
     */
    public SignupPage() {
        initComponents();
    }
    boolean validation(){
        if(txtfname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter first name");
            return false;
        }
        if(txtlname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter last name");
            return false;
        }
        if(txtusername.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter username");
            return false;
        }
        if(txtpassword.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter password");
            return false;
        }
        if(!txtpassword.getText().equals(txtcpass.getText())){
            Lcpass.setText("password not match");
            return false;
        }
        else{
            Lcpass.setText(""); 
        }
        
        if(!male.isSelected() && !female.isSelected()){
            JOptionPane.showMessageDialog(null, "Please select gender");
            return false;
        }
        return true;
    }
    void InsertIntoSql() {
        int p=(int) (Math.random()*(9999-1001+1)-1001);
        
        try {
            Class.forName("java.sql.DriverManager");
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/assu","sharib","sharib");
            Statement st=con.createStatement();
            String gender=null;
            if(male.isSelected()){
                gender="male";
            }
            else{
                gender="female";
            }
            String sql="insert into data values('"+txtfname.getText()+"','"+txtlname.getText()+"','"+txtusername.getText()+"','"+txtpassword.getText()+"','"+gender+"','"+p+"')";
            st.execute(sql);
            JOptionPane.showMessageDialog(null, "Account created");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        LoginPage lp=new LoginPage();
        dispose();
        lp.show();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rSButtonHover1 = new rojerusan.RSButtonHover();
        rSButtonHover2 = new rojerusan.RSButtonHover();
        jLabel3 = new javax.swing.JLabel();
        Lcpass = new javax.swing.JLabel();
        txtcpass = new javax.swing.JPasswordField();
        txtpassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlname.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtlname.setForeground(new java.awt.Color(102, 102, 102));
        txtlname.setText("Enter lastname");
        txtlname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtlname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlnameMouseClicked(evt);
            }
        });
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, 40));

        txtfname.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtfname.setForeground(new java.awt.Color(102, 102, 102));
        txtfname.setText("Enter firstname");
        txtfname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfnameMouseClicked(evt);
            }
        });
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 150, 40));

        txtusername.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtusername.setForeground(new java.awt.Color(102, 102, 102));
        txtusername.setText("Enter username");
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 340, 40));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(male);
        male.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        male.setForeground(new java.awt.Color(102, 102, 102));
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, 30));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(female);
        female.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        female.setForeground(new java.awt.Color(102, 102, 102));
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Gender :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 50));

        rSButtonHover1.setBackground(new java.awt.Color(0, 181, 204));
        rSButtonHover1.setText("Signup");
        rSButtonHover1.setColorHover(new java.awt.Color(102, 102, 102));
        rSButtonHover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonHover1MouseClicked(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 140, -1));

        rSButtonHover2.setBackground(new java.awt.Color(0, 181, 204));
        rSButtonHover2.setText("X");
        rSButtonHover2.setColorHover(new java.awt.Color(255, 0, 51));
        rSButtonHover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonHover2MouseClicked(evt);
            }
        });
        jPanel1.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 50, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Disk E\\NetBeansProjects\\Chatting group\\user.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        Lcpass.setBackground(new java.awt.Color(255, 255, 255));
        Lcpass.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Lcpass.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(Lcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 160, 30));

        txtcpass.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtcpass.setForeground(new java.awt.Color(102, 102, 102));
        txtcpass.setText("Confirm password");
        txtcpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtcpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcpassMouseClicked(evt);
            }
        });
        jPanel1.add(txtcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 160, 40));

        txtpassword.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword.setText("Enter password");
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 520, 500));

        jPanel2.setBackground(new java.awt.Color(0, 181, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chat (11).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -4, -1, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        setSize(new java.awt.Dimension(818, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonHover2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButtonHover2MouseClicked

    private void rSButtonHover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonHover1MouseClicked
        // TODO add your handling code here
        if(validation()){
            InsertIntoSql();
        }
    }//GEN-LAST:event_rSButtonHover1MouseClicked

    private void txtfnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseClicked
        // TODO add your handling code here:
        txtfname.setText("");
    }//GEN-LAST:event_txtfnameMouseClicked

    private void txtlnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlnameMouseClicked
        // TODO add your handling code here:
        txtlname.setText("");
    }//GEN-LAST:event_txtlnameMouseClicked

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        // TODO add your handling code here:
        txtusername.setText("");
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        txtpassword.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtcpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcpassMouseClicked
        // TODO add your handling code here:
        txtcpass.setText("");
    }//GEN-LAST:event_txtcpassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcpass;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private rojerusan.RSButtonHover rSButtonHover1;
    private rojerusan.RSButtonHover rSButtonHover2;
    private javax.swing.JPasswordField txtcpass;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
