/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;

import Jframe.EventChat;
import Jframe.PublicEvent;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author S
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form Menu_left
     */
    public Chat() {
        initComponents();
        init();
    }
    private void init(){
        Chat_body body=new Chat_body();
        /*setLayout(new MigLayout("fillx","0[fill]0","[]0[100%]0[]"));
        Chat_title chatTitle=new Chat_title();
        Chat_body chatBody=new Chat_body();
        Chat_bottom chatBottom=new Chat_bottom();
        add(chatTitle,"wrap");
        add(chatBody,"wrap");
        add(chatBottom,"h ::50%");*/
        PublicEvent.getInstance().addEventChat(new EventChat() {
            @Override
            public void sentMessage(String text) {
                body.addItemLeft("Han ho gia","Shsrib");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chat_body3 = new frame.Chat_body();
        chat_title2 = new frame.Chat_title();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chat_body3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(chat_title2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chat_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chat_body3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private frame.Chat_body chat_body3;
    private frame.Chat_title chat_title2;
    // End of variables declaration//GEN-END:variables
}
