/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;

import Jframe.ScrollBar;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import myproject.Homepage;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author S
 */
public class Menu_left extends javax.swing.JPanel {

    /**
     * Creates new form Menu_left
     */
    public Menu_left() {
        initComponents();
        init();
        showPeople();
    }
    private void init(){
        sp.setVerticalScrollBar(new ScrollBar());
        menupeople.setLayout(new MigLayout("fillx","0[]0","0[]0"));
    }
    private void showPeople(){
        menupeople.removeAll();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/assu","sharib","sharib");
            java.sql.Statement st=con.createStatement();
            String sql="select username from data";
            java.sql.ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                menupeople.add(new itemPeople(rs.getString(1)), "wrap"); 
            }
            
        }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        refreshmenulist();
    }
    private void showGroup(){
        menupeople.removeAll();
        for(int i=0;i<5;i++){
        menupeople.add(new itemPeople("Group "+i), "wrap");
        }
        refreshmenulist();
    }
    private void showBox(){
        menupeople.removeAll();
        for(int i=0;i<10;i++){
        menupeople.add(new itemPeople("Box "+i), "wrap");
        }
        refreshmenulist();
    }
    private void refreshmenulist(){
        menupeople.repaint();
        menupeople.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        menuChat = new frame.menuButton();
        menuGroup = new frame.menuButton();
        menuBox = new frame.menuButton();
        sp = new javax.swing.JScrollPane();
        menupeople = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(0, 181, 204));

        menu.setOpaque(true);
        menu.setLayout(new java.awt.GridLayout(1, 3));

        menuChat.setText(" ");
        menuChat.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/icons/message (2).png"))); // NOI18N
        menuChat.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/icons/message (3).png"))); // NOI18N
        menuChat.setSelected(true);
        menuChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuChatMouseClicked(evt);
            }
        });
        menu.add(menuChat);

        menuGroup.setIcon(new javax.swing.ImageIcon("C:\\Users\\S\\Downloads\\group (2).png")); // NOI18N
        menuGroup.setText(" ");
        menuGroup.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/icons/group (1).png"))); // NOI18N
        menuGroup.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/icons/group (2).png"))); // NOI18N
        menuGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGroupMouseClicked(evt);
            }
        });
        menu.add(menuGroup);

        menuBox.setIcon(new javax.swing.ImageIcon("C:\\Users\\S\\Downloads\\global-connection (1).png")); // NOI18N
        menuBox.setText(" ");
        menuBox.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/icons/global-connection.png"))); // NOI18N
        menuBox.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/icons/global-connection (1).png"))); // NOI18N
        menuBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBoxMouseClicked(evt);
            }
        });
        menu.add(menuBox);

        sp.setBackground(new java.awt.Color(0, 182, 204));
        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menupeople.setBackground(new java.awt.Color(0, 181, 204));
        menupeople.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        menupeople.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menupeople.setOpaque(true);
        menupeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menupeopleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupeopleLayout = new javax.swing.GroupLayout(menupeople);
        menupeople.setLayout(menupeopleLayout);
        menupeopleLayout.setHorizontalGroup(
            menupeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menupeopleLayout.setVerticalGroup(
            menupeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        sp.setViewportView(menupeople);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sp)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuChatMouseClicked
        // TODO add your handling code here:
        if(!menuChat.isSelected()){
            menuChat.setSelected(true);
            menuGroup.setSelected(false);
            menuBox.setSelected(false);
            showPeople();
        }
    }//GEN-LAST:event_menuChatMouseClicked

    private void menuGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGroupMouseClicked
        // TODO add your handling code here:
        if(!menuGroup.isSelected()){
            menuChat.setSelected(false);
            menuGroup.setSelected(true);
            menuBox.setSelected(false);
            showGroup();
        }
    }//GEN-LAST:event_menuGroupMouseClicked

    private void menuBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBoxMouseClicked
        // TODO add your handling code here:
        if(!menuBox.isSelected()){
            menuChat.setSelected(false);
            menuGroup.setSelected(false);
            menuBox.setSelected(true);
            showBox();
        }
        
    }//GEN-LAST:event_menuBoxMouseClicked

    private void menupeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menupeopleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menupeopleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane menu;
    private frame.menuButton menuBox;
    private frame.menuButton menuChat;
    private frame.menuButton menuGroup;
    private javax.swing.JLayeredPane menupeople;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
